#!/bin/bash

opt_dmatch="^\d\d\d?\d?$"
opt_dexclude="^01$"
while getopts "u" opt; do
  case $opt in
    u)
	opt_UPPER=1
    ;;
    D) opt_DRYRUN=1
    ;;
    *) echo "Invalid option -$OPTARG" >&2
    ;;
  esac
done

shift $(($OPTIND-1))
mysd="$1"

if [ -z "$mysd" ]
then
   echo USAGE: build_list-ini [options] [SD path]
   echo options:
   echo -u Don\'t convert name to Sentence Case
   exit;
fi

num=01

echo [GDMENU]
echo $num.name=GDMENU
echo $num.disc=1/1
echo $num.vga=1
echo $num.region=JUE
echo $num.version=V0.6.0
echo $num.date=20160812
echo 



#mylist=($(/usr/bin/ls -w1 $mysd/ |grep -P "\d\d" |grep -v 01))
#mylist=($(/usr/bin/ls -w1 $mysd/ |grep -P "$opt_dmatch" |grep -v "$opt_dexclude"))
mylist=($(/usr/bin/ls -v -w1 $mysd/ |grep -P "^$opt_dmatch$" |grep -v "$opt_dexclude"))


for i in "${mylist[@]}"; do
mydir=$i
    if [ ${#mydir} == 1 ]
    then 
	    mydir=0${mydir}
	fi

./rom_info -n $i $mysd/$mydir
done
exit 1;
