#!/bin/bash
#/d/git/Dreamcast/GDEMU_SD_BUILDER
#./dcc -i '//10.0.0.109/VG0/ROM/DC_REDUMP_U'  -o "/d/sd"
#find /h  -type d -empty -exec rmdir {} \;

set -x
cp ./gditools/*.py /tmp/tmp_rom/output/
EXE_gdi_utils=/d/git/gdi-utils-master/bin/bin-nodejs/index.js

opt_DRYRUN=0
opt_dmatch="^\d\d\d?\d?$"
opt_dexclude="^01$"
echo "dcc v.01"
while getopts ":i:o:D:" opt; do
  case $opt in
    o)
        mysd="$OPTARG"
    ;;
    i)
        myroms="$OPTARG"
    ;;
    D)
        opt_DRYRUN=1
    ;;
    \?) echo "Invalid option -$OPTARG" >&2
    ;;
  esac
done


if [ -z "$myroms" ] || [ -z "$mysd" ]
then
   echo USAGE: dcc -i inputdir -o outputdir
fi
myroms=$(printf "%q" "$myroms")
mysd=$(printf "%q" "$mysd")

mylist=($myroms/*)
#strip path
mylist=( "${mylist[@]##*/}" )

echo Total: ${#mylist[@]} 

mkdir -p /tmp/tmp_rom/unzip
mkdir -p /tmp/tmp_rom/output


for fname in "${mylist[@]}"
do
   : 

   fname= $(printf "%q" "$fname")
    mkdir "/tmp/tmp_rom/unzip/$fname"
    mkdir "/tmp/tmp_rom/output/$fname"
    unzip -e "$myroms/$fname" -d "/tmp/tmp_rom/unzip/$fname"
#    unzip -e "$myroms/$fname" -d "/tmp/tmp_rom/unzip/rom"
#	fname=rom
	
    mygdi=$(ls "/tmp/tmp_rom/unzip/$fname/"*.gdi)
    echo MYGDI:$mygdi
    echo $fname
#    echo node $EXE_gdi_utils "'$mygdi'" 0 $(printf "%q" "/tmp/tmp_rom/output/$fname")
#    echo node $EXE_gdi_utils "'$mygdi'" 0 $(printf "%q" "/tmp/tmp_rom/output/$fname") |sh
    echo node $EXE_gdi_utils "'$mygdi'" 0  "/tmp/tmp_rom/output/$fname"
    echo node $EXE_gdi_utils "'$mygdi'" 0  "/tmp/tmp_rom/output/$fname" |sh
    
    if [ ! -z "/tmp/tmp_rom/output/$fname/disc.gdi" ] 
    then
        #mkdir "/tmp/tmp_rom/output/$fname/"
##        cp "/tmp/tmp_rom/unzip/$fname/"* "/tmp/tmp_rom/output/$fname/" 
        mv "/tmp/tmp_rom/unzip/$fname/"* "/tmp/tmp_rom/output/$fname/"
        mv "/tmp/tmp_rom/output/$fname/"*.gdi "/tmp/tmp_rom/output/$fname/"disc.gdi

    fi
	
	pushd "/tmp/tmp_rom/output/$fname/"
	mv ../*.py .
	pwd
	echo 	python ./gdishrink.py *.gdi
	python ./gdishrink.py *.gdi
	mv *.py ../
	rm *.pyc

#    pushd gditools
#    python gdishrink.py "/tmp/tmp_rom/output/$fname/disc.gdi"
    popd

    
    LIST=$(/usr/bin/ls -v "$mysd/" |grep -P "^$opt_dmatch$")
    LIST=($LIST)
			if [ -z $LIST ]; then LIST=(1); fi
    lf=${LIST[${#LIST[@]}-1]}
    #lf=${LIST[${#LIST[@]}]}
    lf=$(echo $lf | sed 's/^0*//')
    ((lf++))
#    lf=$(printf $opt_DIGIT $lf)
			if [ ${#lf} == 1 ]; then lf=0${lf}; fi

    echo Moving to SD: $lf
	mv "/tmp/tmp_rom/output/$fname" "$mysd/$lf"
#!!!    rm -rf "/tmp/tmp_rom/unzip/$fname"
exit 1;
done
