#!/bin/bash
#reorder dirs on sd based on name in DC track03.iso in each folder
#mysd=/f

opt_DRYRUN=0
opt_dmatch="^\d\d\d?\d?$"
opt_dexclude="^01$"
while getopts "D" opt; do
  case $opt in
    D) opt_DRYRUN=1
    ;;
    *) echo "Invalid option -$OPTARG" >&2
    ;;
  esac
done

shift $(($OPTIND-1))
mysd="$1"

if [ -z "$mysd" ]
then
   echo USAGE: reorder [options] [SD path]
   echo options:
   echo -D Dry run
   exit;
fi


#find "$mysd"  -type d -empty -exec rmdir {} \;

#mylist=($(/usr/bin/ls -w1 $mysd/ |grep -P "\d\d" |grep -v 01))
mylist=($(/usr/bin/ls -v -w1 $mysd/ |grep -P "^$opt_dmatch$" |grep -v "$opt_dexclude"))

declare -a num_name

#put names into assoc array dir=name
for i in "${mylist[@]}"
do
   : 
   mytrack=$(ls "$mysd/$i/track03".*)
   echo $mytrack!!!!
   #dd if="$mysd/$i/track03.*" skip=128 count=50  bs=1 status=none | sed -e 's/[[:space:]]*$//'	
   #myname=$(dd if="$mysd/$i/track03.*" skip=128 count=50  bs=1 status=none | sed -e 's/[[:space:]]*$//')
   myname=$(dd if="$mytrack" skip=128 count=50  bs=1 status=none | sed -e 's/[[:space:]]*$//')	
   num_name[${i#0}]="$myname"
done

#rename all folders
for i in "${mylist[@]}"
do
   : 
    cmd="mv "$mysd/$i" "$mysd/$i.new""
    if [ $opt_DRYRUN == 1 ]
    then
        echo $cmd
    else
        echo $cmd
        $cmd
    fi
done

#keys sorted by name to new array
IFS=$'\n'; set -f
sorted_keys=($(
    for key in "${!num_name[@]}"; do
      printf '%s:%s\n' "$key" "${num_name[$key]}"
    done | sort -t : -k 2 | sed 's/:.*//'
    ))
unset IFS; set +f

for key in "${!sorted_keys[@]}"; do
#    od=$(printf $opt_DIGIT ${sorted_keys[$key]})
#    dd=$(printf $opt_DIGIT $((key+2)))
    od=${sorted_keys[$key]}
    if [ ${#od} == 1 ]
    then 
	    od=0${od}
	fi
    dd=$((key+2))
    if [ ${#dd} == 1 ]
    then 
	    dd=0${dd}
	fi

    cmd="mv "$mysd/$od.new" "$mysd/$dd""

    if [ $opt_DRYRUN == 1 ]
    then
        echo $cmd
    else
        echo $cmd
        $cmd
    fi

done

exit 1;
